spring.datasource.url=jdbc:h2:file:./data/pcb_calculator;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.flyway.user=sa
spring.flyway.password=
spring.flyway.schemas=public
spring.flyway.url=jdbc:h2:file:./data/pcb_calculator;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=validate
spring.logging.level.org.flywaydb=DEBUG

server.port=8180
app.api.base-url=http://localhost:8180/api

app.jwt.secret=my-super-secret-key-for-jwt-that-is-at-least-256-bits-long-and-i-aint-gonna-change-it
app.jwt.expiration-ms=86400000