CREATE TABLE producers (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    contact_person  VARCHAR(255),
    email           VARCHAR(255) UNIQUE NOT NULL,
    phone           VARCHAR(255),
    password_hash   VARCHAR(255) NOT NULL,
    is_active       BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tariffs (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producer_id         INT NOT NULL REFERENCES producers(id) ON DELETE CASCADE,
    name                VARCHAR(255) NOT NULL,
    base_price_per_cm2  DECIMAL(10,4) NOT NULL,
    extra_layer_price   DECIMAL(10,4) DEFAULT 0.0000,
    expedited_fee       DECIMAL(10,4) DEFAULT 0.0000,
    setup_cost          DECIMAL(10,4) DEFAULT 0.0000,
    min_quantity        INT DEFAULT 1,
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_tariffs_producer_id ON tariffs(producer_id);

CREATE TABLE limitations (
    id                      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tariff_id               INT UNIQUE NOT NULL REFERENCES tariffs(id) ON DELETE CASCADE,
    min_track_width_mm      DECIMAL(10,4) NOT NULL,
    min_clearance_mm        DECIMAL(10,4) NOT NULL,
    min_hole_diameter_mm    DECIMAL(10,4) NOT NULL,
    max_layers              INT NOT NULL,
    supported_materials     TEXT ARRAY,
    supported_finishes      TEXT ARRAY,
    supports_blind_via      BOOLEAN DEFAULT FALSE,
    supports_buried_via     BOOLEAN DEFAULT FALSE
);